apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        params:
        stepTemplate:
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-admin:0.0.168
          name: admin-log
          script: |
            #!/usr/bin/env sh
            echo "viewing the git operator boot job log for commit sha: $PULL_BASE_SHA"
            jx admin log --commit-sha $PULL_BASE_SHA
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
