apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata:
         annotations:
          iam.amazonaws.com/role: ClusterA.jx.JenkinsX
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.2.22
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: node:12-slim
          name: build-npm-install
          resources: {}
          script: |
            #!/bin/sh
            npm install
        - image: node:12-slim
          name: build-npm-test
          resources: {}
          script: |
            #!/bin/sh
            CI=true DISPLAY=:99 npm test
        - image: gcr.io/jenkinsxio/jx-registry:0.0.12
          name: check-registry
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-container-build
          resources: {}
          env:
            - name: NPM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: web2-npm-token
                  key: token
            - name: HTTPS_GIT_CREDS
              valueFrom:
                secretKeyRef:
                  name: tekton-git
                  key: password
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --build-arg=DOCKER_REGISTRY=$DOCKER_REGISTRY/jx \
            --build-arg=NPM_TOKEN=$NPM_TOKEN \
            --build-arg=HTTPS_GIT_CREDS=$HTTPS_GIT_CREDS \
            --context=/workspace/source \
            --cache=true \
            --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME \
            --dockerfile=Dockerfile \
            --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        - image: ghcr.io/jenkins-x/jx-preview:0.0.171
          name: promote-jx-preview
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            jx preview create
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 20m0s
status: {}
