apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jstrachan/jx3-pipeline-catalog/tasks/ml-python-gpu-service/release.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
          workingDir: /workspace/source
        steps:
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - name: setup-step3
          resources: {}
        - name: build-flake8
          resources: {}
        - name: build-testing
          resources: {}
        - name: build-container-build
          resources: {}
        - name: promote-changelog
          resources: {}
        - name: promote-helm-release
          resources: {}
        - name: promote-step9
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
