apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: chart
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/jx-release-version:2.2.1
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx-release-version > VERSION
        - image: ghcr.io/jenkins-x/jx-boot:3.1.217
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: golang:1.15
          name: release-binary
          resources: {}
          script: |
            #!/usr/bin/env bash
            source .jx/variables.sh
            make release
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-and-push-image
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=Dockerfile --destination=gcr.io/$DOCKER_REGISTRY_ORG/$REPO_NAME:$VERSION
        - image: jnorwood/helm-docs:v1.4.0
          name: chart-docs
          resources: {}
          script: |
            #!/bin/ash
            if [ -d "charts/$REPO_NAME" ]; then cd charts/$REPO_NAME
            helm-docs; else echo no charts; fi
        - image: gcr.io/jenkinsxio/jx-changelog:0.0.30
          name: changelog
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh

            if [ -d "charts/$REPO_NAME" ]; then
            sed -i -e "s/^version:.*/version: $VERSION/" ./charts/$REPO_NAME/Chart.yaml
            sed -i -e "s/repository:.*/repository: $DOCKER_REGISTRY\/$DOCKER_REGISTRY_ORG\/$APP_NAME/" ./charts/$REPO_NAME/values.yaml
            sed -i -e "s/tag:.*/tag: $VERSION/" ./charts/$REPO_NAME/values.yaml;
            else echo no charts; fi

            jx changelog create --verbose --header-file=hack/changelog-header.md --version=$VERSION --rev=$PULL_BASE_SHA --output-markdown=changelog.md --update-release=false
        - image: ghcr.io/jenkins-x/jx-cli:3.1.217
          name: release-chart
          resources: {}
          script: |
            #!/usr/bin/env bash
            if [ -d "charts/$REPO_NAME" ]; then source .jx/variables.sh
            cd charts/$REPO_NAME
            make release; else echo no charts; fi
        - image: goreleaser/goreleaser:v0.155.0
          name: upload-binaries
          env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: tekton-git
                key: password
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh

            git add * || true
            git commit -a -m "chore: release $VERSION" --allow-empty
            git tag -fa v$VERSION -m "Release version $VERSION"
            git push origin v$VERSION

            export BRANCH=$(git rev-parse --abbrev-ref HEAD)
            export BUILDDATE=$(date)
            export REV=$(git rev-parse HEAD)
            export GOVERSION="1.15"
            export ROOTPACKAGE="github.com/$REPO_OWNER/$REPO_NAME"
            goreleaser release
        - image: google/cloud-sdk:slim
          name: multi-arch-images
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            gcloud builds submit --config cloudbuild.yaml --project jenkinsxio --substitutions=_VERSION="$VERSION"
        - command:
          - jx-updatebot
          - pr
          image: gcr.io/jenkinsxio/jx-updatebot:0.0.49
          name: promote-release
          resources: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
