apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone.yaml
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136
          name: tag-with-new-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step next-version --use-git-tag-only --tag
        - image: gcr.io/jenkinsxio/jx-boot:3.0.738
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: gcr.io/kaniko-project/executor:multi-arch-v1.3.0
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: promote-changelog
          resources: {}
          script: |
            #!/bin/bash
            source /workspace/source/.jx/variables.sh
            jx step changelog --version v${VERSION}
        - image: gcr.io/jenkinsxio/jx-cli:3.0.705
          name: promote-helm-release
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx gitops helm release
        - image: gcr.io/jenkinsxio/jx-cli:3.0.705
          name: promote-jx-promote
          resources: {}
          script: |
            #!/bin/bash
            source /workspace/source/.jx/variables.sh
            jx promote -b --all-auto --timeout 1h --no-poll

  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
