apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: git-clone
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/git-clone/git-clone.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: next-version
      runAfter:
      - git-clone
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/cwp/release/next-version.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: jx-variables
      runAfter:
      - next-version
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/cwp/release/jx-variables.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-mvn-deploy
      runAfter:
      - jx-variables
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/cwp/release/build-mvn-deploy.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: check-registry
      runAfter:
      - build-mvn-deploy
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/cwp/release/check-registry.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-container-build
      runAfter:
      - check-registry
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/cwp/release/build-container-build.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: promote-changelog
      runAfter:
      - build-container-build
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/cwp/release/promote-changelog.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: promote-step6
      runAfter:
      - promote-changelog
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/cwp/release/promote-step6.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: promote-jx
      runAfter:
      - promote-step6
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/cwp/release/promote-jx.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    workspaces:
    - name: pipeline-ws
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
  workspaces:
  - name: pipeline-ws
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
status: {}
