apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/60bed6408732c1eda91a15713f51a9f97dcb1757/tasks/git-clone/git-clone.yaml
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/jx-release-version:2.2.5
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx-release-version > VERSION
        - image: ghcr.io/jenkins-x/jx-boot:3.1.333
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables

  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
