apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
  - name: output
    description: The git repo will be cloned onto the volume backing this workspace
    mountPath: /workspace
  steps:
  - script: |
      #!/usr/bin/env bash
      export SUBDIR="source"
      echo "git cloning url: $REPO_URL version $PULL_BASE_SHA to dir: $SUBDIR"
      git config --global --add user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
      git config --global --add user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}
      git config --global credential.helper store
      git clone $REPO_URL $SUBDIR
      cd $SUBDIR
      git checkout $PULL_BASE_SHA
      echo "checked out revision: $PULL_BASE_SHA to dir: $SUBDIR"
    image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
    name: git-clone
    resources: { }
    workingDir: /workspace
  - args:
    - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
    command:
    - /bin/sh
    - -c
    image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
    name: setup-builder-home
    resources: {}
