apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/60bed6408732c1eda91a15713f51a9f97dcb1757/task/git-clone/git-clone-pr.yaml
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: test
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.1.217
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - env:
          - name: GH_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                key: password
                name: bdd-pipeline-token-github
          image: gcr.io/jenkinsxio/jx-go-maven:latest
          name: runci
          resources: {}
          script: |
            #!/usr/bin/env bash
            source .jx/variables.sh
            echo running bdd test $JOB_NAME
            cd /workspace/source/.lighthouse/jenkins-x/tests
            make test
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
