apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/release.yaml@a5ab19ebc5a074e0402c5016b11bc11b32cc5c83
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - env:
          - name: GH_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                key: password
                name: bdd-git
          image: ghcr.io/jenkins-x/jx-go-maven:3.2.197
          name: runci
          resources: {}
          script: |
            #!/usr/bin/env bash
            source .jx/variables.sh
            echo running bdd test $JOB_NAME
            cd /workspace/source/.lighthouse/jenkins-x/tests
            go mod download
            make test
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
