apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: git-clone
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/git-clone/git-clone.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: next-version
      runAfter:
      - git-clone
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/go/release/next-version.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: jx-variables
      runAfter:
      - next-version
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/go/release/jx-variables.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: promote-changelog
      runAfter:
      - jx-variables
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/go/release/promote-changelog.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: promote-pullrequest
      runAfter:
      - promote-changelog
      taskSpec:
        metadata: {}
        spec: null
        stepTemplate:
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.10.88
          name: promote-pullrequest
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh

            git clone https://github.com/jenkins-x/$REPO_NAME new-main
            cd new-main
            sed -i -e "s|uses:jenkins-x/jx3-pipeline-catalog/tasks/go/release.yaml@.*|uses:jenkins-x/jx3-pipeline-catalog/tasks/go/release.yaml@$PULL_BASE_SHA|" environment/.lighthouse/jenkins-x/pullrequest.yaml

            git add * || true
            git commit -a -m "chore: upgrade environment pull request to $PULL_BASE_SHA" --allow-empty
            git push
        workspaces:
        - description: The workspace used to store the cloned git repository and the
            generated files
          mountPath: /workspace
          name: output
    workspaces:
    - name: pipeline-ws
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
  workspaces:
  - name: pipeline-ws
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 328761Ki
      status: {}
status: {}
