apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/60bed6408732c1eda91a15713f51a9f97dcb1757/task/git-clone/git-clone.yaml
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: changelog
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.1.217
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: gcr.io/jenkinsxio/builder-jx:0.1.792
          name: changelog
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step changelog --verbose --version ${VERSION} --rev v${VERSION}
        - image: ghcr.io/jenkins-x/jx-boot:3.1.217
          name: promote
          resources: {}
          script: |
            #!/bin/sh
            ./.lighthouse/jenkins-x/promote.sh
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
