name: pullrequest_remote_work_flow
on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      image_tag:
        type: string
        required: true
      repository:
        type: string
        required: true
      comment:
        type: string
        required: true

    secrets:
      pullrequest_remote_work_flow_secret:
        required: true

env:
  GIT_COMMENT: ${{ inputs.comment }}
  IMAGE_NAME: ${{ inputs.image_name }}
  IMAGE_TAG: ${{ inputs.image_tag }}
  REPOSITORY: ${{ inputs.repository }}
  COMMENT: ${{ inputs.comment }}


jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    outputs:
      extracted_image_name: ${{ steps.extract_image.outputs.EXTRACTED_IMAGE_NAME }}
      
    steps:
      - name: Extract Image Name And Env 
        id: extract_image_name_and_env
        run: |
          EXTRACTED_IMAGE_NAME=$(echo "${{ inputs.image_name }}" | rev | cut -d'/' -f1 | rev)
          echo "EXTRACTED_IMAGE_NAME=${EXTRACTED_IMAGE_NAME}" >> "$GITHUB_OUTPUT"
          build_env=$(echo ${{ inputs.comment }} | awk -F':' '{print $2}')
          echo "BUILD_ENV=jx-${build_env}" >> "$GITHUB_OUTPUT"
          
      - name: Check Outputs
        id: checkOutputs
        run: |-
          echo "Image Name: ${{ steps.extract_image_name_and_env.outputs.EXTRACTED_IMAGE_NAME }}"
          echo "Image Tag: ${{ env.IMAGE_TAG }}"
          echo "repository: ${{ env.REPOSITORY }}"
          echo "comment: ${{ env.COMMENT }}"
          echo "Build Env: ${{ steps.extract_image_name_and_env.outputs.BUILD_ENV }}"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml
      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.pullrequest_remote_work_flow_secret }}
      - run: |
          pwd
          ls -ltrh
          find . -type f -name "pr-script.py"
          #python /home/runner/work/bb-l1-kube-controller/bb-l1-kube-controller/versionStream/src/script/pr-script.py ${{ steps.extract_image_name_and_env.outputs.BUILD_ENV }} ${{ steps.extract_image_name_and_env.outputs.EXTRACTED_IMAGE_NAME }} ${{ env.IMAGE_TAG }}
          python ./versionStream/src/script/pr-script.py ${{ steps.extract_image_name_and_env.outputs.BUILD_ENV }} ${{ steps.extract_image_name_and_env.outputs.EXTRACTED_IMAGE_NAME }} ${{ env.IMAGE_TAG }}
          cat ./helmfiles/jx-qa04/helmfile.yaml
          cd versionStream/src/script
          git config -l

      - name: Create branch
        id: Create_branch
        run: |
          #RANDOM_NUMBER="pr-${{ github.sha }}-${{ github.run_id }}"
          RANDOM_NUMBER="pr-Testx1-${{ github.run_id }}"
          echo "BRANCH_NAME=$RANDOM_NUMBER" >> $GITHUB_OUTPUT
          echo "Creating a new branch $RANDOM_NUMBER"
          #git checkout -b $RANDOM_NUMBER  

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.pullrequest_remote_work_flow_secret }}
          commit-message: "chore: update image tag ${{ steps.extract_image_name_and_env.outputs.EXTRACTED_IMAGE_NAME }} ${{ env.IMAGE_TAG }} ${{ steps.extract_image_name_and_env.outputs.BUILD_ENV }}"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: ${{ steps.Create_branch.outputs.BRANCH_NAME }}
          title: 'chore: promote ${{ steps.extract_image_name_and_env.outputs.EXTRACTED_IMAGE_NAME }} to version ${{ env.IMAGE_TAG }}'
          body: |
            Update report
            - GITHUB_REF_NAME: ${{ github.ref_name }}
            - GITHUB_ACTOR: ${{ github.actor }}
            - GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}
            - DATE: $(date)
            - Auto-generated by Create Pull Request Action

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            do-not-merge
            ${{ steps.extract_image_name_and_env.outputs.BUILD_ENV }}

      #create step to run python sript int his path "/versionStream/src/script/pr-script.py"
      # - name: Create branch
      #   id: Create_branch
      #   run: |
      #     #RANDOM_NUMBER="pr-${{ github.sha }}-${{ github.run_id }}"
      #     RANDOM_NUMBER="pr-Testx1-${{ github.run_id }}"
      #     echo "BRANCH_NAME=$RANDOM_NUMBER" >> $GITHUB_OUTPUT
      #     echo "Creating a new branch $RANDOM_NUMBER"
      #     #git checkout -b $RANDOM_NUMBER

      # - name: Change Immage Tags
      #   run: |
      #     pwd
      #     ls -ltrh
      #     find . -type f -name "pr-script.py"
      #     #python /home/runner/work/bb-l1-kube-controller/bb-l1-kube-controller/versionStream/src/script/pr-script.py ${{ steps.extract_image_name_and_env.outputs.BUILD_ENV }} ${{ steps.extract_image_name_and_env.outputs.EXTRACTED_IMAGE_NAME }} ${{ env.IMAGE_TAG }}
      #     python ./versionStream/src/script/pr-script.py ${{ steps.extract_image_name_and_env.outputs.BUILD_ENV }} ${{ steps.extract_image_name_and_env.outputs.EXTRACTED_IMAGE_NAME }} ${{ env.IMAGE_TAG }}
      #     cat ./helmfiles/jx-qa04/helmfile.yaml
      #     cd versionStream/src/script
      #     git config -l
         

      # - name: Push the new branch
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PULLREQUEST_REMOTE_WORK_FLOW_SECRET }}
      #   run: |
      #       git add .
      #       git commit -m "chore: update image tag ${{ steps.extract_image_name_and_env.outputs.BUILD_ENV }} ${{ steps.extract_image_name_and_env.outputs.EXTRACTED_IMAGE_NAME }} ${{ env.IMAGE_TAG }}"
      #       #git push --set-upstream origin ${{ steps.Create_branch.outputs.BRANCH_NAME }}
      #       git push https://${{ secrets.PULLREQUEST_REMOTE_WORK_FLOW_SECRET }}@github.com/${{ github.repository }} ${{ steps.Create_branch.outputs.BRANCH_NAME }}
      # - name: Commit & Push changes
      #   uses: actions-js/push@master
      #   with:
      #     github_token: ${{ secrets.PULLREQUEST_REMOTE_WORK_FLOW_SECRET }}
      #     message: "chore: update image tag ${{ steps.extract_image_name_and_env.outputs.BUILD_ENV }} ${{ steps.extract_image_name_and_env.outputs.EXTRACTED_IMAGE_NAME }} ${{ env.IMAGE_TAG }}"
      #     branch: ${{ steps.Create_branch.outputs.BRANCH_NAME }}
          


      # - name: create pull request
      #   run: gh pr create -B main -H ${{ steps.Set_branch_name.outputs.BRANCH_NAME }} --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.PULLREQUEST_REMOTE_WORK_FLOW_SECRET }}


      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ secrets.pullrequest_remote_work_flow_secret }}
      #     commit-message: Update Tag
      #     #committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      #     #author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
      #     #signoff: false
      #     branch: Test
      #     title: '[Example] Update report'
      #     body: |
      #       Update report
      #       - Updated with *today's* date
      #       - Auto-generated by [create-pull-request][1]

      #       [1]: https://github.com/peter-evans/create-pull-request
      #     labels: |
      #       report
      #       automated pr
      #     milestone: 1
      #     draft: false








          


