name: Workflow for using Snyk 
on:
  workflow_call:
    inputs:
      workload_identity_provider:
        type: string
      service_account:
        type: string
    secrets:
      SNYK_TOKEN:
        description: "Snyk token"
        required: true

jobs:
  security:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        tags: localhost:5000/${{ github.event.repository.name }}:latest
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        SNYK_REGISTRY_USERNAME: "oauth2accesstoken"
        SNYK_REGISTRY_PASSWORD: "${{ steps.auth.outputs.access_token }}"
      with:
        image: localhost:5000/${{ github.event.repository.name }}:latest
        args: --file=Dockerfile
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
